"""rlte -- Reinforcement Learning for Trade Execution.

Reference implementation scaffold generated by ArXivist from:
Cheridito & Weiss (2026), "Reinforcement Learning for Trade Execution with
Market and Limit Orders", arXiv:2507.06345.
"""
__version__ = "0.1.0"
