from setuptools import find_packages, setup

setup(
    name="dnabert2",
    version="0.1.0",
    description="Reproduction of DNABERT-2 (arXiv:2306.15006), generated by ArXivist",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1",
        "transformers>=4.35",
        "einops>=0.7",
        "datasets>=2.14",
        "huggingface_hub>=0.19",
        "scikit-learn>=1.3",
        "pandas>=2.0",
        "pyyaml>=6.0",
        "tqdm>=4.66",
        "numpy>=1.24",
    ],
)
