from setuptools import find_packages, setup

setup(
    name="hyenadna",
    version="0.1.0",
    description="Reproduction of HyenaDNA (arXiv:2306.15794), generated by ArXivist",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1",
        "transformers>=4.35",
        "huggingface_hub>=0.19",
        "datasets>=2.14",
        "genomic-benchmarks>=0.0.9",
        "scikit-learn>=1.3",
        "pyyaml>=6.0",
        "tqdm>=4.66",
        "numpy>=1.24",
        "einops>=0.7",
        "omegaconf>=2.3",
        "torchvision>=0.16",
    ],
)
