"""
Standalone loss functions matching the SIR's mathematical_spec, exposed as
plain NumPy functions independent of any specific circuit class (useful for
unit tests and for the VariationalTrainer in trainer.py).

SIR reference: mathematical_spec "QCBM regularised cross-entropy training
loss", "CRCA controlled-rotation MSE training loss", "KL divergence
diagnostic".
"""

from __future__ import annotations

import numpy as np


def qcbm_cross_entropy(
    p_theta: np.ndarray, p_target: np.ndarray, eps_num: float = 1e-8
) -> float:
    """L_QCBM(theta) = - sum_x P_target(x) log(P_theta(x) + eps_num).

    Args:
        p_theta: Born distribution generated by the circuit, shape [2**n].
        p_target: target finite-grid distribution, shape [2**n], sums to 1.
        eps_num: numerical floor (ASSUMED value; not given exactly in paper).

    Returns:
        Scalar loss.
    """
    return -float(np.sum(p_target * np.log(p_theta + eps_num)))


def kl_divergence_diagnostic(
    p_theta: np.ndarray, p_target: np.ndarray, eps_num: float = 1e-8
) -> float:
    """KL_eps(P_target || P_theta), a post-training diagnostic (not the
    training objective itself)."""
    mask = p_target > 0
    return float(np.sum(p_target[mask] * np.log(p_target[mask] / (p_theta[mask] + eps_num))))


def crca_mse_loss(f_phi: np.ndarray, f_target: np.ndarray) -> float:
    """L_f(phi) = mean((F_phi(x) - f_target(x))^2)."""
    return float(np.mean((f_phi - f_target) ** 2))
