"""
Classical variational-parameter training loop for QCBM (G_theta) and CRCA
(R_v, R_p, R_q) blocks.

The paper (Section 3.2.3) states the training objectives (cross-entropy for
QCBM, MSE for CRCA) explicitly but does not name the classical optimizer,
learning rate, or exact iteration counts (SIR training_pipeline confidence =
0.5; see architecture_plan.json risk_assessment). This trainer therefore
exposes the optimizer as a config-selectable choice (default: a simple
Adam implementation using parameter-shift gradients, since all gates used in
this paper's ansatze are single-parameter Pauli rotations for which the
parameter-shift rule gives *exact* analytic gradients) so results can be
regenerated with an alternative optimizer if the authors' own code
(Borràs, 2026, github.com/gborras10/Quantum-CVA) specifies one differently.

SIR reference: architecture.modules "training/trainer.py",
implementation_assumptions[0], [1].
"""

from __future__ import annotations

from typing import Callable, List, Optional, Tuple

import numpy as np


ParamShiftGradFn = Callable[[np.ndarray], np.ndarray]


class AdamOptimizer:
    """Minimal Adam optimizer (Kingma & Ba, 2015 default hyperparameters),
    used because the paper does not name an optimizer (ASSUMED, config.yaml
    `training.optimizer: adam`, SIR confidence 0.4).
    """

    def __init__(
        self,
        lr: float = 0.05,
        beta1: float = 0.9,
        beta2: float = 0.999,
        eps: float = 1e-8,
    ) -> None:
        self.lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.eps = eps
        self.m: np.ndarray = None
        self.v: np.ndarray = None
        self.t = 0

    def step(self, params: np.ndarray, grad: np.ndarray) -> np.ndarray:
        """Apply one Adam update step and return the new parameters."""
        if self.m is None:
            self.m = np.zeros_like(params)
            self.v = np.zeros_like(params)
        self.t += 1
        self.m = self.beta1 * self.m + (1 - self.beta1) * grad
        self.v = self.beta2 * self.v + (1 - self.beta2) * (grad**2)
        m_hat = self.m / (1 - self.beta1**self.t)
        v_hat = self.v / (1 - self.beta2**self.t)
        return params - self.lr * m_hat / (np.sqrt(v_hat) + self.eps)


def parameter_shift_gradient(
    loss_fn: Callable[[np.ndarray], float], params: np.ndarray, shift: float = np.pi / 2
) -> np.ndarray:
    """Exact analytic gradient via the parameter-shift rule, valid because
    every gate in the QCBM/CRCA ansatze (RX, RZ, RZZ) is generated by a
    Pauli operator with eigenvalues +/-1:

        d/d(theta_i) L = [L(theta_i + pi/2) - L(theta_i - pi/2)] / 2

    Cost: 2 * len(params) loss evaluations per gradient. Exact but expensive
    for circuits with many parameters (e.g. R_v's 84 parameters at the
    paper's full six-qubit scale) -- see `spsa_gradient` for a cheaper
    stochastic alternative used when parameter-shift is computationally
    intractable within a practical time budget.

    Args:
        loss_fn: scalar loss as a function of the full parameter vector.
        params: current parameter values.
        shift: shift amount (pi/2 for standard Pauli-rotation gates).

    Returns:
        Gradient array, same shape as params.
    """
    grad = np.zeros_like(params)
    for i in range(len(params)):
        plus = params.copy()
        plus[i] += shift
        minus = params.copy()
        minus[i] -= shift
        grad[i] = 0.5 * (loss_fn(plus) - loss_fn(minus))
    return grad


def spsa_gradient(
    loss_fn: Callable[[np.ndarray], float],
    params: np.ndarray,
    c: float = 0.1,
    rng: Optional[np.random.Generator] = None,
) -> np.ndarray:
    """Simultaneous Perturbation Stochastic Approximation (SPSA) gradient
    estimate (Spall, 1992): a stochastic gradient using only 2 loss
    evaluations *regardless of the number of parameters*.

        grad_i ~ [L(theta + c*Delta) - L(theta - c*Delta)] / (2*c*Delta_i),
        Delta_i in {-1, +1} uniformly at random

    NOT specified by the paper (which names no optimizer at all -- SIR
    training_pipeline confidence 0.5). This is used here purely as a
    practical necessity: exact parameter-shift gradients for the full
    six-qubit R_v block (84 parameters) cost ~86s *per gradient step*
    (168 statevector-simulated loss evaluations over the 64-point grid),
    making the paper's stated ~4200-iteration training schedule take on the
    order of 100 hours. SPSA reduces this to ~1s/step (2 evaluations) at the
    cost of a noisier, biased gradient estimate -- a documented
    compute-tractability trade-off, not a claim about what the paper's
    authors actually used.

    Args:
        loss_fn: scalar loss as a function of the full parameter vector.
        params: current parameter values.
        c: perturbation magnitude.
        rng: optional NumPy random generator.

    Returns:
        Stochastic gradient estimate, same shape as params.
    """
    rng = rng or np.random.default_rng()
    delta = rng.choice([-1.0, 1.0], size=params.shape)
    loss_plus = loss_fn(params + c * delta)
    loss_minus = loss_fn(params - c * delta)
    return (loss_plus - loss_minus) / (2 * c * delta)


class VariationalTrainer:
    """Trains QCBM and CRCA variational parameters against their respective
    finite-grid classical targets (Section 3.2.3).

    Args:
        optimizer: classical optimizer name (only "adam" implemented; see
            `_make_optimizer`).
        learning_rate: Adam learning rate.
        seed: RNG seed for parameter initialisation and SPSA perturbations.
        gradient_method: "parameter_shift" (exact, 2*n_params loss evals per
            step) or "spsa" (stochastic, 2 loss evals per step regardless of
            n_params). SPSA is a documented compute-tractability trade-off
            for large blocks like R_v (84 params at the paper's full
            six-qubit scale) -- see `spsa_gradient` docstring. NOT specified
            by the paper (SIR training_pipeline confidence 0.5).
        spsa_c: SPSA perturbation magnitude (only used if gradient_method="spsa").
    """

    def __init__(
        self,
        optimizer: str = "adam",
        learning_rate: float = 0.05,
        seed: int = 100000,
        gradient_method: str = "parameter_shift",
        spsa_c: float = 0.1,
    ) -> None:
        self.optimizer_name = optimizer
        self.learning_rate = learning_rate
        self.seed = seed
        self.gradient_method = gradient_method
        self.spsa_c = spsa_c
        self._rng = np.random.default_rng(seed)

    def __repr__(self) -> str:  # noqa: D105
        return (
            f"VariationalTrainer(optimizer={self.optimizer_name!r}, "
            f"lr={self.learning_rate}, gradient_method={self.gradient_method!r})"
        )

    def _init_params(self, n_params: int) -> np.ndarray:
        rng = np.random.default_rng(self.seed)
        return rng.uniform(-np.pi, np.pi, n_params)

    def _make_optimizer(self):
        if self.optimizer_name == "adam":
            return AdamOptimizer(lr=self.learning_rate)
        raise ValueError(
            f"Unsupported optimizer '{self.optimizer_name}'. The paper does "
            f"not name its optimizer (SIR confidence 0.4); only 'adam' "
            f"(ASSUMED default) is implemented. Extend AdamOptimizer or add "
            f"a scipy.optimize.minimize wrapper here for alternatives such "
            f"as L-BFGS or COBYLA."
        )

    def _compute_gradient(self, loss_fn: Callable[[np.ndarray], float], params: np.ndarray) -> np.ndarray:
        if self.gradient_method == "parameter_shift":
            return parameter_shift_gradient(loss_fn, params)
        if self.gradient_method == "spsa":
            return spsa_gradient(loss_fn, params, c=self.spsa_c, rng=self._rng)
        raise ValueError(f"Unknown gradient_method '{self.gradient_method}'")

    def _train_loop(
        self,
        loss_fn: Callable[[np.ndarray], float],
        n_params: int,
        num_iterations: int,
        log_every_n_steps: int,
        tag: str,
        init_params: Optional[np.ndarray] = None,
        optimizer_state: Optional[AdamOptimizer] = None,
    ) -> Tuple[np.ndarray, List[float], AdamOptimizer]:
        params = init_params if init_params is not None else self._init_params(n_params)
        optimizer = optimizer_state if optimizer_state is not None else self._make_optimizer()
        history = []

        for step in range(num_iterations):
            loss = loss_fn(params)
            history.append(loss)
            grad = self._compute_gradient(loss_fn, params)
            params = optimizer.step(params, grad)
            if step % log_every_n_steps == 0:
                print(f"[{tag}] step {step:5d}  loss={loss:.6e}")

        return params, history, optimizer

    def train_qcbm(
        self,
        loss_fn: Callable[[np.ndarray], float],
        n_params: int,
        num_iterations: int,
        log_every_n_steps: int = 50,
        init_params: Optional[np.ndarray] = None,
        optimizer_state: Optional[AdamOptimizer] = None,
    ) -> Tuple[np.ndarray, List[float], AdamOptimizer]:
        """Train QCBM parameters by minimising the cross-entropy loss.

        Args:
            loss_fn: callable params -> scalar cross-entropy loss (bind the
                target distribution via functools.partial or a closure before
                passing it in).
            n_params: number of trainable parameters (circuit.num_parameters).
            num_iterations: number of optimisation steps (ASSUMED value in
                config.yaml, read off Figure 8/9 -- not stated numerically
                in the paper).
            log_every_n_steps: logging frequency.
            init_params: optional warm-start parameters (for resuming a
                chunked/checkpointed run).
            optimizer_state: optional warm-start Adam optimizer state (for
                resuming with correct momentum).

        Returns:
            (trained_params, loss_history, optimizer_state) -- the returned
            optimizer_state can be passed back in to resume training exactly.
        """
        return self._train_loop(
            loss_fn, n_params, num_iterations, log_every_n_steps, "QCBM", init_params, optimizer_state
        )

    def train_crca(
        self,
        loss_fn: Callable[[np.ndarray], float],
        n_params: int,
        num_iterations: int,
        log_every_n_steps: int = 50,
        init_params: Optional[np.ndarray] = None,
        optimizer_state: Optional[AdamOptimizer] = None,
    ) -> Tuple[np.ndarray, List[float], AdamOptimizer]:
        """Train a CRCA block (R_v, R_p, or R_q) by minimising its MSE loss.

        Args:
            loss_fn: callable params -> scalar MSE loss.
            n_params: number of trainable parameters.
            num_iterations: number of optimisation steps (ASSUMED, see
                config.yaml comments).
            log_every_n_steps: logging frequency.
            init_params: optional warm-start parameters (for resuming a
                chunked/checkpointed run).
            optimizer_state: optional warm-start Adam optimizer state.

        Returns:
            (trained_params, loss_history, optimizer_state).
        """
        return self._train_loop(
            loss_fn, n_params, num_iterations, log_every_n_steps, "CRCA", init_params, optimizer_state
        )
